# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - build/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    file_names: false
    always_use_package_imports: true
