name: co2_sensor_viewer
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: "^3.1.0"

dependencies:
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  usb_serial: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.0
  pedantic_mono: ^1.24.0+1
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0

flutter:
  uses-material-design: true
