name: co2_sensor_viewer
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: "^3.1.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  pedantic_mono: ^1.24.0+1

flutter:
  uses-material-design: true
