name: Auto Format & Auto Generate Code

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
  push:
    branches:
      - main
      - develop

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Fetch flutter config
        uses: kuhnroyal/flutter-fvm-config-action@v1
      # https://github.com/subosito/flutter-action
      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get
      - name: build_runner
        run: flutter pub run build_runner build -d

      - name: format
        run: scripts/format.sh

      # 変更が発生した場合は プルリクエストを作成
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          commit-message: "Auto format"
          committer: "GitHub Actions <noreply@github.com>"
          base: ${{ github.head_ref }}
          branch: "auto-format/${{ github.sha }}"
          title: "Auto format - ref: ${{ github.ref_name }}"
          body: "Auto format by GitHub Actions on ${{ github.sha }}\nby: ${{github.actor}}"